/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GURestApi.Client.OpenAPIDateConverter;

namespace GURestApi.Model
{
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CommandType
    {
        [EnumMember(Value = "exec_command")]
        ExecCommand = 1,
        [EnumMember(Value = "open_command")]
        OpenCommand,
        [EnumMember(Value = "close_command")]
        CloseCommand,
        [EnumMember(Value = "start_command")]
        StartCommand,
        [EnumMember(Value = "stop_command")]
        StopCommand,
        [EnumMember(Value = "add_tags_command")]
        AddTagsCommand,
        [EnumMember(Value = "del_tags_command")]
        DelTagsCommand,
        [EnumMember(Value = "download_file_command")]
        DownloadFileCommand,
        [EnumMember(Value = "upload_file_command")]
        UploadFileCommand,
    }

    /// <summary>
    /// Command
    /// </summary>
    [DataContract]
    public partial class Command : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Command" /> class.
        /// </summary>
        protected Command(CommandType type)
        {
            Type = type;
        }

        public CommandType Type {get; private set;}

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Command {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
