/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GURestApi.Client.OpenAPIDateConverter;

namespace GURestApi.Model
{
    /// <summary>
    /// Exec environment type.  * hd - Host Direct mode * docker - Docker Container mode * wasm - WebAssembly mode * vm - virtual machine mode.
    /// </summary>
    /// <value>Exec environment type.  * hd - Host Direct mode * docker - Docker Container mode * wasm - WebAssembly mode * vm - virtual machine mode.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum EnvType
    {
        /// <summary>
        /// Enum Hd for value: hd
        /// </summary>
        [EnumMember(Value = "hd")]
        Hd = 1,

        /// <summary>
        /// Enum Docker for value: docker
        /// </summary>
        [EnumMember(Value = "docker")]
        Docker = 2,

        /// <summary>
        /// Enum Wasm for value: wasm
        /// </summary>
        [EnumMember(Value = "wasm")]
        Wasm = 3,

        /// <summary>
        /// Enum Graphne for value: graphne
        /// </summary>
        [EnumMember(Value = "graphne")]
        Graphne = 4,

        /// <summary>
        /// Enum Vm for value: vm
        /// </summary>
        [EnumMember(Value = "vm")]
        Vm = 5

    }

}
