/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = gu_rest_api.Client.OpenAPIDateConverter;

namespace gu_rest_api.Model
{
    /// <summary>
    /// Defines FileFormat
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum FileFormat
    {
        /// <summary>
        /// Enum Raw for value: raw
        /// </summary>
        [EnumMember(Value = "raw")]
        Raw = 1,

        /// <summary>
        /// Enum Tar for value: tar
        /// </summary>
        [EnumMember(Value = "tar")]
        Tar = 2

    }

}
