/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GURestApi.Client.OpenAPIDateConverter;

namespace GURestApi.Model
{
    /// <summary>
    /// General information about GU subnetwork node
    /// </summary>
    [DataContract]
    public partial class PeerInfo :  IEquatable<PeerInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PeerInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PeerInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PeerInfo" /> class.
        /// </summary>
        /// <param name="nodeName">Node name or hostname from reverse dns if node name is not set.</param>
        /// <param name="peerAddr">node address from current connection formated as &lt;ip-addr&gt;:&lt;port&gt; (required).</param>
        /// <param name="tags">tags.</param>
        public PeerInfo(string nodeName = default(string), string peerAddr = default(string), List<string> tags = default(List<string>))
        {
            // to ensure "peerAddr" is required (not null)
            if (peerAddr == null)
            {
                throw new InvalidDataException("peerAddr is a required property for PeerInfo and cannot be null");
            }
            else
            {
                this.PeerAddr = peerAddr;
            }
            this.NodeName = nodeName;
            this.Tags = tags;
        }
        
        /// <summary>
        /// Node name or hostname from reverse dns if node name is not set
        /// </summary>
        /// <value>Node name or hostname from reverse dns if node name is not set</value>
        [DataMember(Name="nodeName", EmitDefaultValue=false)]
        public string NodeName { get; set; }

        /// <summary>
        /// node address from current connection formated as &lt;ip-addr&gt;:&lt;port&gt;
        /// </summary>
        /// <value>node address from current connection formated as &lt;ip-addr&gt;:&lt;port&gt;</value>
        [DataMember(Name="peerAddr", EmitDefaultValue=false)]
        public string PeerAddr { get; set; }

        /// <summary>
        /// node public key hash in etherium format
        /// </summary>
        /// <value>node public key hash in etherium format</value>
        [DataMember(Name="nodeId", EmitDefaultValue=false)]
        public string NodeId { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PeerInfo {\n");
            sb.Append("  NodeName: ").Append(NodeName).Append("\n");
            sb.Append("  PeerAddr: ").Append(PeerAddr).Append("\n");
            sb.Append("  NodeId: ").Append(NodeId).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PeerInfo);
        }

        /// <summary>
        /// Returns true if PeerInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of PeerInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PeerInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NodeName == input.NodeName ||
                    (this.NodeName != null &&
                    this.NodeName.Equals(input.NodeName))
                ) && 
                (
                    this.PeerAddr == input.PeerAddr ||
                    (this.PeerAddr != null &&
                    this.PeerAddr.Equals(input.PeerAddr))
                ) && 
                (
                    this.NodeId == input.NodeId ||
                    (this.NodeId != null &&
                    this.NodeId.Equals(input.NodeId))
                ) && 
                (
                    this.Tags == input.Tags ||
                    this.Tags != null &&
                    this.Tags.SequenceEqual(input.Tags)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NodeName != null)
                    hashCode = hashCode * 59 + this.NodeName.GetHashCode();
                if (this.PeerAddr != null)
                    hashCode = hashCode * 59 + this.PeerAddr.GetHashCode();
                if (this.NodeId != null)
                    hashCode = hashCode * 59 + this.NodeId.GetHashCode();
                if (this.Tags != null)
                    hashCode = hashCode * 59 + this.Tags.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
