/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GURestApi.Client.OpenAPIDateConverter;

namespace GURestApi.Model
{
    /// <summary>
    /// VolumeDef
    /// </summary>
    [DataContract]
    public partial class VolumeDef :  IEquatable<VolumeDef>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VolumeDef" /> class.
        /// </summary>
        /// <param name="bindRw">bindRw.</param>
        public VolumeDef(VolumeDefBindRw bindRw = default(VolumeDefBindRw))
        {
            this.BindRw = bindRw;
        }
        
        /// <summary>
        /// Gets or Sets BindRw
        /// </summary>
        [DataMember(Name="BindRw", EmitDefaultValue=false)]
        public VolumeDefBindRw BindRw { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VolumeDef {\n");
            sb.Append("  BindRw: ").Append(BindRw).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VolumeDef);
        }

        /// <summary>
        /// Returns true if VolumeDef instances are equal
        /// </summary>
        /// <param name="input">Instance of VolumeDef to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VolumeDef input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BindRw == input.BindRw ||
                    (this.BindRw != null &&
                    this.BindRw.Equals(input.BindRw))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BindRw != null)
                    hashCode = hashCode * 59 + this.BindRw.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
