/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GURestApi.Api;
using GURestApi.Model;
using GURestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GURestApi.Test
{
    /// <summary>
    ///  Class for testing BuildInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BuildInfoTests
    {
        // TODO uncomment below to declare an instance variable for BuildInfo
        //private BuildInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BuildInfo
            //instance = new BuildInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BuildInfo
        /// </summary>
        [Test]
        public void BuildInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BuildInfo
            //Assert.IsInstanceOfType<BuildInfo> (instance, "variable 'instance' is a BuildInfo");
        }


        /// <summary>
        /// Test the property 'Ts'
        /// </summary>
        [Test]
        public void TsTest()
        {
            // TODO unit test for the property 'Ts'
        }
        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Test]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }
        /// <summary>
        /// Test the property 'CommitHash'
        /// </summary>
        [Test]
        public void CommitHashTest()
        {
            // TODO unit test for the property 'CommitHash'
        }

    }

}
