/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GURestApi.Api;
using GURestApi.Model;
using GURestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GURestApi.Test
{
    /// <summary>
    ///  Class for testing Command
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CommandTests
    {
        // TODO uncomment below to declare an instance variable for Command
        //private Command instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Command
            //instance = new Command();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Command
        /// </summary>
        [Test]
        public void CommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Command
            //Assert.IsInstanceOfType<Command> (instance, "variable 'instance' is a Command");
        }


        /// <summary>
        /// Test the property 'Exec'
        /// </summary>
        [Test]
        public void ExecTest()
        {
            // TODO unit test for the property 'Exec'
        }
        /// <summary>
        /// Test the property 'Open'
        /// </summary>
        [Test]
        public void OpenTest()
        {
            // TODO unit test for the property 'Open'
        }
        /// <summary>
        /// Test the property 'Close'
        /// </summary>
        [Test]
        public void CloseTest()
        {
            // TODO unit test for the property 'Close'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'Stop'
        /// </summary>
        [Test]
        public void StopTest()
        {
            // TODO unit test for the property 'Stop'
        }
        /// <summary>
        /// Test the property 'AddTags'
        /// </summary>
        [Test]
        public void AddTagsTest()
        {
            // TODO unit test for the property 'AddTags'
        }
        /// <summary>
        /// Test the property 'DelTags'
        /// </summary>
        [Test]
        public void DelTagsTest()
        {
            // TODO unit test for the property 'DelTags'
        }
        /// <summary>
        /// Test the property 'DownloadFile'
        /// </summary>
        [Test]
        public void DownloadFileTest()
        {
            // TODO unit test for the property 'DownloadFile'
        }
        /// <summary>
        /// Test the property 'UploadFile'
        /// </summary>
        [Test]
        public void UploadFileTest()
        {
            // TODO unit test for the property 'UploadFile'
        }

    }

}
