/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gu_rest_api.Api;
using gu_rest_api.Model;
using gu_rest_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gu_rest_api.Test
{
    /// <summary>
    ///  Class for testing DeploymentSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeploymentSpecTests
    {
        // TODO uncomment below to declare an instance variable for DeploymentSpec
        //private DeploymentSpec instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeploymentSpec
            //instance = new DeploymentSpec();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeploymentSpec
        /// </summary>
        [Test]
        public void DeploymentSpecInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeploymentSpec
            //Assert.IsInstanceOfType<DeploymentSpec> (instance, "variable 'instance' is a DeploymentSpec");
        }


        /// <summary>
        /// Test the property 'EnvType'
        /// </summary>
        [Test]
        public void EnvTypeTest()
        {
            // TODO unit test for the property 'EnvType'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }

    }

}
