/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GURestApi.Api;
using GURestApi.Model;
using GURestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GURestApi.Test
{
    /// <summary>
    ///  Class for testing DockerNetDef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DockerNetDefTests
    {
        // TODO uncomment below to declare an instance variable for DockerNetDef
        //private DockerNetDef instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DockerNetDef
            //instance = new DockerNetDef();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DockerNetDef
        /// </summary>
        [Test]
        public void DockerNetDefInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DockerNetDef
            //Assert.IsInstanceOfType<DockerNetDef> (instance, "variable 'instance' is a DockerNetDef");
        }


        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Test]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }

    }

}
