/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gu_rest_api.Api;
using gu_rest_api.Model;
using gu_rest_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gu_rest_api.Test
{
    /// <summary>
    ///  Class for testing DockerCreateOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DockerCreateOptionsTests
    {
        // TODO uncomment below to declare an instance variable for DockerCreateOptions
        //private DockerCreateOptions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DockerCreateOptions
            //instance = new DockerCreateOptions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DockerCreateOptions
        /// </summary>
        [Test]
        public void DockerCreateOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DockerCreateOptions
            //Assert.IsInstanceOfType<DockerCreateOptions> (instance, "variable 'instance' is a DockerCreateOptions");
        }


        /// <summary>
        /// Test the property 'Volumes'
        /// </summary>
        [Test]
        public void VolumesTest()
        {
            // TODO unit test for the property 'Volumes'
        }
        /// <summary>
        /// Test the property 'Cmd'
        /// </summary>
        [Test]
        public void CmdTest()
        {
            // TODO unit test for the property 'Cmd'
        }
        /// <summary>
        /// Test the property 'Net'
        /// </summary>
        [Test]
        public void NetTest()
        {
            // TODO unit test for the property 'Net'
        }

    }

}
