/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GURestApi.Api;
using GURestApi.Model;
using GURestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GURestApi.Test
{
    /// <summary>
    ///  Class for testing ExecCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExecCommandTests
    {
        // TODO uncomment below to declare an instance variable for ExecCommand
        //private ExecCommand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExecCommand
            //instance = new ExecCommand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExecCommand
        /// </summary>
        [Test]
        public void ExecCommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExecCommand
            //Assert.IsInstanceOfType<ExecCommand> (instance, "variable 'instance' is a ExecCommand");
        }


        /// <summary>
        /// Test the property 'Executable'
        /// </summary>
        [Test]
        public void ExecutableTest()
        {
            // TODO unit test for the property 'Executable'
        }
        /// <summary>
        /// Test the property 'Args'
        /// </summary>
        [Test]
        public void ArgsTest()
        {
            // TODO unit test for the property 'Args'
        }

    }

}
