/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gu_rest_api.Api;
using gu_rest_api.Model;
using gu_rest_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gu_rest_api.Test
{
    /// <summary>
    ///  Class for testing FileFormat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileFormatTests
    {
        // TODO uncomment below to declare an instance variable for FileFormat
        //private FileFormat instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileFormat
            //instance = new FileFormat();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileFormat
        /// </summary>
        [Test]
        public void FileFormatInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileFormat
            //Assert.IsInstanceOfType<FileFormat> (instance, "variable 'instance' is a FileFormat");
        }



    }

}
