/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GURestApi.Api;
using GURestApi.Model;
using GURestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GURestApi.Test
{
    /// <summary>
    ///  Class for testing HubSessionTouchCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HubSessionTouchCommandTests
    {
        // TODO uncomment below to declare an instance variable for HubSessionTouchCommand
        //private HubSessionTouchCommand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HubSessionTouchCommand
            //instance = new HubSessionTouchCommand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HubSessionTouchCommand
        /// </summary>
        [Test]
        public void HubSessionTouchCommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HubSessionTouchCommand
            //Assert.IsInstanceOfType<HubSessionTouchCommand> (instance, "variable 'instance' is a HubSessionTouchCommand");
        }


        /// <summary>
        /// Test the property 'KeepUntil'
        /// </summary>
        [Test]
        public void KeepUntilTest()
        {
            // TODO unit test for the property 'KeepUntil'
        }

    }

}
