/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gu_rest_api.Api;
using gu_rest_api.Model;
using gu_rest_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gu_rest_api.Test
{
    /// <summary>
    ///  Class for testing HubSessionCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HubSessionCommandTests
    {
        // TODO uncomment below to declare an instance variable for HubSessionCommand
        //private HubSessionCommand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HubSessionCommand
            //instance = new HubSessionCommand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HubSessionCommand
        /// </summary>
        [Test]
        public void HubSessionCommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HubSessionCommand
            //Assert.IsInstanceOfType<HubSessionCommand> (instance, "variable 'instance' is a HubSessionCommand");
        }

        /// <summary>
        /// Test deserialize a HubSessionTouchCommand from type HubSessionCommand
        /// </summary>
        [Test]
        public void HubSessionTouchCommandDeserializeFromHubSessionCommandTest()
        {
            // TODO uncomment below to test deserialize a HubSessionTouchCommand from type HubSessionCommand
            //Assert.IsInstanceOf<HubSessionCommand>(JsonConvert.DeserializeObject<HubSessionCommand>(new HubSessionTouchCommand().ToJson()));
        }

        /// <summary>
        /// Test the property 'CommandType'
        /// </summary>
        [Test]
        public void CommandTypeTest()
        {
            // TODO unit test for the property 'CommandType'
        }
        /// <summary>
        /// Test the property 'Ts'
        /// </summary>
        [Test]
        public void TsTest()
        {
            // TODO unit test for the property 'Ts'
        }

    }

}
