/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gu_rest_api.Api;
using gu_rest_api.Model;
using gu_rest_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gu_rest_api.Test
{
    /// <summary>
    ///  Class for testing PeerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PeerInfoTests
    {
        // TODO uncomment below to declare an instance variable for PeerInfo
        //private PeerInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PeerInfo
            //instance = new PeerInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PeerInfo
        /// </summary>
        [Test]
        public void PeerInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PeerInfo
            //Assert.IsInstanceOfType<PeerInfo> (instance, "variable 'instance' is a PeerInfo");
        }


        /// <summary>
        /// Test the property 'NodeName'
        /// </summary>
        [Test]
        public void NodeNameTest()
        {
            // TODO unit test for the property 'NodeName'
        }
        /// <summary>
        /// Test the property 'PeerAddr'
        /// </summary>
        [Test]
        public void PeerAddrTest()
        {
            // TODO unit test for the property 'PeerAddr'
        }
        /// <summary>
        /// Test the property 'NodeId'
        /// </summary>
        [Test]
        public void NodeIdTest()
        {
            // TODO unit test for the property 'NodeId'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

    }

}
