/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GURestApi.Api;
using GURestApi.Model;
using GURestApi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GURestApi.Test
{
    /// <summary>
    ///  Class for testing UploadFileCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UploadFileCommandTests
    {
        // TODO uncomment below to declare an instance variable for UploadFileCommand
        //private UploadFileCommand instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UploadFileCommand
            //instance = new UploadFileCommand();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UploadFileCommand
        /// </summary>
        [Test]
        public void UploadFileCommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UploadFileCommand
            //Assert.IsInstanceOfType<UploadFileCommand> (instance, "variable 'instance' is a UploadFileCommand");
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'FilePath'
        /// </summary>
        [Test]
        public void FilePathTest()
        {
            // TODO unit test for the property 'FilePath'
        }

    }

}
