/* 
 * Golem unlimited low level hub API
 *
 * API description in Markdown.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using gu_rest_api.Api;
using gu_rest_api.Model;
using gu_rest_api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace gu_rest_api.Test
{
    /// <summary>
    ///  Class for testing VolumeDef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VolumeDefTests
    {
        // TODO uncomment below to declare an instance variable for VolumeDef
        //private VolumeDef instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VolumeDef
            //instance = new VolumeDef();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VolumeDef
        /// </summary>
        [Test]
        public void VolumeDefInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VolumeDef
            //Assert.IsInstanceOfType<VolumeDef> (instance, "variable 'instance' is a VolumeDef");
        }


        /// <summary>
        /// Test the property 'BindRw'
        /// </summary>
        [Test]
        public void BindRwTest()
        {
            // TODO unit test for the property 'BindRw'
        }

    }

}
